version: "0.2"
ignorePaths:
  - archive
  - dist
  - node_modules
dictionaries:
  - en_US
  - softwareTerms
  - bash
  - node
  - npm
  - html
  - css
  - typescript
  - filetypes
words:
  - brolog
  - btns
  - casbin
  - cgqaq
  - chatgpt
  - errcode
  - errmsg
  - gptapi
  - justjavac
  - msgtype
  - npmmirror
  - openai
  - preinstall
  - qrcode
  - wechat
  - wechaty
ignoreWords:
  - trivago
  - zhengxs
