version: '0.2'
ignorePaths:
  - archive
  - dist
  - node_modules
dictionaries:
  - en_US
  - softwareTerms
  - bash
  - node
  - npm
  - html
  - css
  - typescript
  - filetypes
words:
  - brolog
  - btns
  - casbin
  - cgqaq
  - chatgpt
  - downurl
  - errcode
  - errmsg
  - gptapi
  - ismp
  - ismv
  - justjavac
  - kugou
  - msgtype
  - mvdata
  - mvicon
  - npmmirror
  - openai
  - preinstall
  - qrcode
  - showtype
  - songname
  - wechat
  - wechaty
ignoreWords:
  - trivago
  - zhengxs
